# Generated by Django 3.1.7 on 2021-04-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragonuser',
            name='photo_url',
            field=models.URLField(blank=True, default='https://cdn3.iconfinder.com/data/icons/galaxy-open-line-gradient-i/200/contacts-512.png'),
        ),
    ]
