# Generated by Django 3.1.7 on 2021-04-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '__first__'),
        ('game', '0002_auto_20210415_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameCharacters',
            field=models.ManyToManyField(blank=True, related_name='pawns', to='characters.Character'),
        ),
    ]
